### PR TITLE
Build: Remove duplicated node job

### PR DESCRIPTION
**Pull request by cotsog**

### CODE REVIEW

**Comment by Berkmann18** [comment]
Thank for the help, I'll keep an eye on the TravisCI and see how it goes.

**Comment by Berkmann18** [comment]
@cotsog Is it normal that the release step happens before the tests?
I've just [seen this](https://travis-ci.org/Berkmann18/nclr/builds/473948302) for [this](https://github.com/Berkmann18/nclr) and was wondering why the release stage happened before the test stage.

**Comment by cotsog** [comment]
@Berkmann18 Sorry for the delay of my reply. Could you point me to a build where that happened? Thanks!

**Comment by Berkmann18** [comment]
@cotsog Sure, here's [one](https://travis-ci.org/Berkmann18/ServerBuilder/builds/477939828) with [this configuration](https://travis-ci.org/Berkmann18/ServerBuilder/builds/477939828/config), It happened in other repos with slightly different configurations (e.g: using `jest` instead of `mocha` and/or having more node versions in the test phase).

**Comment by Berkmann18** [comment]
Friendly ping @cotsog!

**Comment by cotsog** [comment]
@Berkmann18 Sorry for the delay again!

Could you try to add the following to your .travis.yml file?

```yaml
stages:
  - name: test
  - name: release
    if: branch = master
```

**Comment by cotsog** [comment]
For a little bit more background, stages defined in `stages:` will be executed before the default `test` stage. See https://docs.travis-ci.com/user/build-stages/#specifying-stage-order-and-conditions.

**Comment by Berkmann18** [comment]
> For a little bit more background, stages defined in `stages:` will be executed before the default `test` stage.

Ooh! that explains why.
Anyway, it's fixed now! Thank you again.

Is it okay, if I add you to the contributor's list?

**Comment by cotsog** [comment]
Glad to hear it's fixed!

And it would be an honor to on your project's contributors list. 😊

**Comment by Berkmann18** [comment]
@allcontributors Please add @cotsog for infra

**Pull request merged**
